Fix: Prevent Elytra Swap While Player is in Fluids
sakura-ryoko/tweakeroo pull request #27
Opened 2024-07-17 18:19 UTC by GabiBizdoc

### Description
This pull request fixes the issue described in issue #25, where the Elytra would incorrectly swap when the player is in fluid.

### Changes Made
- Added a check to prevent elytra switch when the player is in fluid.

2024-07-17 22:41 UTC, zly2006 commented
`isSwiming` is not needed if you checked `isInFluid`, and I do not agree with changing the other code.

2024-07-17 23:00 UTC, zly2006 requested changes

2024-07-17 23:00 UTC, zly2006 commented on src/main/java/fi/dy/masa/tweakeroo/mixin/MixinClientPlayerEntity.java
> +        if (!isElytraEquipped || (isChestPlateEquipped || autoSwitchIsElytra)) {
this condition can be simplified to `!isElytraEquipped`, why add brackets in `||`s?

2024-07-18 00:15 UTC, sakura-ryoko commented
Superseded by PR # 29

2024-07-18 00:15 UTC, closed without merging